env:
  global:
    - "JRUBY_OPTS=-Xcext.enabled=true"
rvm:
  - 1.8.7
  - ree
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4.2
  - 2.5.1
  - 2.6
  - ruby-head
  - jruby
branches:
  only:
    - master
before_script:
- if (ruby -e "exit RUBY_VERSION.to_f >= 2.3"); then export RUBYOPT="--enable-frozen-string-literal"; fi; echo $RUBYOPT
matrix:
  allow_failures:
    - rvm: 2.6
    - rvm: ruby-head
    - rvm: jruby
script: "rake test" # test:scanners"
sudo: false
